name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Baixa o repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask groq python-decouple requests werkzeug
          pip install pytest

      # Roda os testes
      - name: Run tests
        run: pytest -v
